apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods
    presubmits:
      hxia209/openshift-prow-demo:
      - name: test-presubmit
        decorate: true
        always_run: true
        skip_report: true
        spec:
          containers:
          - image: alpine
            command: ["/bin/printenv"]
    postsubmits:
      hxia209/openshift-prow-demo:
      - name: test-postsubmit
        decorate: true
        spec:
          containers:
          - image: alpine
            command: ["/bin/printenv"]